# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/himan/OneDrive/Desktop/finaYRpro/trafficLight - Copy/trafficLight.cache/wt} [current_project]
set_property parent.project_path {C:/Users/himan/OneDrive/Desktop/finaYRpro/trafficLight - Copy/trafficLight.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/himan/OneDrive/Desktop/finaYRpro/trafficLight - Copy/trafficLight.srcs/sources_1/new/spi.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/himan/OneDrive/Desktop/finaYRpro/trafficLight - Copy/trafficLight.srcs/constrs_1/new/ConstraintsXDC.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/himan/OneDrive/Desktop/finaYRpro/trafficLight - Copy/trafficLight.srcs/constrs_1/new/ConstraintsXDC.xdc}}]


synth_design -top spi_system -part xc7a35tcsg324-1


write_checkpoint -force -noxdef spi_system.dcp

catch { report_utilization -file spi_system_utilization_synth.rpt -pb spi_system_utilization_synth.pb }
